version: "2"

volumes:
  ? mongo_data

services:

  mongodb:
    expose:
      - "27017"
    hostname: mongodb
    image: mongo:4.4
    stdin_open: true
    tty: true
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  orion:
    command:  -dbhost mongodb -port 1026 -logLevel DEBUG
    depends_on:
      - mongodb
    expose:
        - "1026"
    hostname: orion
    image: fiware/orion:latest
    ports:
      - "1026:1026"
    stdin_open: true
    tty: true

  iotagent-lora:
    depends_on:
      - mongodb
      - orion
    entrypoint: bin/iotagent-lora docker/config-docker.js
    hostname: iotagent-lora
    image: iot-agent
    ports:
      - "4061:4041"
    stdin_open: true
    tty: true