version: "3.5"

volumes:
  ? mongo_data

services:
  mongodb:
    hostname: mongodb
    container_name: mongodb-backpedal
    image: mongo:4.4
    volumes:
      - mongo_data:/data/db
    expose:
      - "27017"
    ports:
      - "27017:27017"

  orion:
    hostname: orion
    container_name: fiware-orion
    image: fiware/orion:latest
    command: -dbhost mongodb -port 1026 -logLevel DEBUG
    depends_on:
      - mongodb
    expose:
      - "1026"
    ports:
      - "1026:1026"

  iotagent-lora:
    hostname: iotagent-lora
    container_name: iotagent-ttn
    image: iot-agent
    depends_on:
      - mongodb
      - orion
    entrypoint: bin/iotagent-lora docker/config-docker.js
    ports:
      - "4061:4041"
